import { lazy, type ComponentType } from 'react'
import type { Lang } from '@/lib/i18n'

// Alle Widgets lazy: sie machen den Großteil des Bundles aus, aber pro
// Modulseite wird höchstens eine Handvoll gebraucht. Named-Export -> default
// mappen, weil React.lazy nur default-Exporte versteht.
export const WIDGETS: Record<string, ComponentType<{ lang: Lang }>> = {
  'vlan-switch': lazy(() => import('@/widgets/VlanSwitch').then((m) => ({ default: m.VlanSwitch }))),
  'frame-builder': lazy(() => import('@/widgets/FrameBuilder').then((m) => ({ default: m.FrameBuilder }))),
  'osi-model': lazy(() => import('@/widgets/osi/OsiWidget').then((m) => ({ default: m.OsiModel }))),
  'mac-learning': lazy(() => import('@/widgets/switch/MacLearningWidget').then((m) => ({ default: m.MacLearning }))),
  'subnet-calc': lazy(() => import('@/widgets/subnet/SubnetWidget').then((m) => ({ default: m.Subnet }))),
  'arp-demo': lazy(() => import('@/widgets/arp/ArpWidget').then((m) => ({ default: m.Arp }))),
  'routing-demo': lazy(() => import('@/widgets/router/RoutingWidget').then((m) => ({ default: m.Routing }))),
  'nat-demo': lazy(() => import('@/widgets/nat/NatWidget').then((m) => ({ default: m.Nat }))),
  'dns-demo': lazy(() => import('@/widgets/dns/DnsWidget').then((m) => ({ default: m.Dns }))),
  'dhcp-demo': lazy(() => import('@/widgets/dhcp/DhcpWidget').then((m) => ({ default: m.Dhcp }))),
  'ports-demo': lazy(() => import('@/widgets/ports/PortsWidget').then((m) => ({ default: m.Ports }))),
  'icmp-demo': lazy(() => import('@/widgets/icmp/IcmpWidget').then((m) => ({ default: m.Icmp }))),
  'firewall-demo': lazy(() => import('@/widgets/firewall/FirewallWidget').then((m) => ({ default: m.Firewall }))),
  'ipv6-demo': lazy(() => import('@/widgets/ipv6/Ipv6Widget').then((m) => ({ default: m.Ipv6 }))),
  'wlan-demo': lazy(() => import('@/widgets/wlan/WlanWidget').then((m) => ({ default: m.Wlan }))),
  'vpn-demo': lazy(() => import('@/widgets/vpn/VpnWidget').then((m) => ({ default: m.Vpn }))),
  'troubleshoot-demo': lazy(() => import('@/widgets/troubleshoot/TroubleshootWidget').then((m) => ({ default: m.Troubleshoot }))),
  'capstone-demo': lazy(() => import('@/widgets/capstone/CapstoneWidget').then((m) => ({ default: m.Capstone }))),
  'wireshark-demo': lazy(() => import('@/widgets/wireshark/WiresharkWidget').then((m) => ({ default: m.Wireshark }))),
  'learning-route': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-route" {...p} /> }))),
  'learning-policy': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-policy" {...p} /> }))),
  'learning-dhcp': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-dhcp" {...p} /> }))),
  'learning-dns': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-dns" {...p} /> }))),
  'learning-packet': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-packet" {...p} /> }))),
  'learning-subnet': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-subnet" {...p} /> }))),
  'learning-filter': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-filter" {...p} /> }))),
  'learning-attack': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-attack" {...p} /> }))),
  'learning-ipv6': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-ipv6" {...p} /> }))),
  'learning-evidence': lazy(() => import('@/widgets/learning/LearningLab').then((m) => ({ default: (p: { lang: Lang }) => <m.LearningLabForId id="learning-evidence" {...p} /> }))),
  'visual-topology': lazy(() => import('@/widgets/visuals/NetworkVisuals').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualForId id="visual-topology" {...p} /> }))),
  'visual-encapsulation': lazy(() => import('@/widgets/visuals/NetworkVisuals').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualForId id="visual-encapsulation" {...p} /> }))),
  'visual-subnet-map': lazy(() => import('@/widgets/visuals/NetworkVisuals').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualForId id="visual-subnet-map" {...p} /> }))),
  'visual-firewall-flow': lazy(() => import('@/widgets/visuals/NetworkVisuals').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualForId id="visual-firewall-flow" {...p} /> }))),
  'visual-dns-tree': lazy(() => import('@/widgets/visuals/NetworkVisuals').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualForId id="visual-dns-tree" {...p} /> }))),
  'visual-vlan-tag-path': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-vlan-tag-path" {...p} /> }))),
  'visual-arp-resolution': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-arp-resolution" {...p} /> }))),
  'visual-route-match': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-route-match" {...p} /> }))),
  'visual-nat-translation': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-nat-translation" {...p} /> }))),
  'visual-dhcp-lease': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-dhcp-lease" {...p} /> }))),
  'visual-tcp-session': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-tcp-session" {...p} /> }))),
  'visual-ipv6-autoconfig': lazy(() => import('@/widgets/visuals/NetworkVisualsMore').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualMoreForId id="visual-ipv6-autoconfig" {...p} /> }))),
  'visual-bitmask': lazy(() => import('@/widgets/visuals/NetworkVisualsDynamics').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualDynamicForId id="visual-bitmask" {...p} /> }))),
  'visual-broadcast-storm': lazy(() => import('@/widgets/visuals/NetworkVisualsDynamics').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualDynamicForId id="visual-broadcast-storm" {...p} /> }))),
  'visual-dhcp-relay': lazy(() => import('@/widgets/visuals/NetworkVisualsDynamics').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualDynamicForId id="visual-dhcp-relay" {...p} /> }))),
  'visual-ephemeral-ports': lazy(() => import('@/widgets/visuals/NetworkVisualsDynamics').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualDynamicForId id="visual-ephemeral-ports" {...p} /> }))),
  'visual-stateful-firewall': lazy(() => import('@/widgets/visuals/NetworkVisualsDynamics').then((m) => ({ default: (p: { lang: Lang }) => <m.NetworkVisualDynamicForId id="visual-stateful-firewall" {...p} /> }))),
  'tokenizer-demo': lazy(() => import('@/widgets/tokenizer/TokenizerWidget').then((m) => ({ default: m.Tokenizer }))),
  'cli-simulator': lazy(() => import('@/widgets/claudecli/ClaudeCliWidget').then((m) => ({ default: m.ClaudeCli }))),
  'permission-simulator': lazy(() => import('@/widgets/permissions/PermissionWidget').then((m) => ({ default: m.PermissionSim }))),
  'hook-lifecycle': lazy(() => import('@/widgets/hooklife/HookLifecycleWidget').then((m) => ({ default: m.HookLifecycle }))),
  'mcp-inspector': lazy(() => import('@/widgets/mcpinspector/McpInspectorWidget').then((m) => ({ default: m.McpInspector }))),
  'agent-orchestrator': lazy(() => import('@/widgets/orchestrator/OrchestratorWidget').then((m) => ({ default: m.Orchestrator }))),
  'ansible-lab': lazy(() => import('@/widgets/ansiblelab/AnsibleLabWidget').then((m) => ({ default: m.AnsibleLab }))),
  'crypto-hash': lazy(() => import('@/widgets/pki/HashWidget').then((m) => ({ default: m.HashLab }))),
  'crypto-aead': lazy(() => import('@/widgets/pki/AeadWidget').then((m) => ({ default: m.AeadLab }))),
  'crypto-keyexchange': lazy(() => import('@/widgets/pki/KeyExchangeWidget').then((m) => ({ default: m.KeyExchange }))),
  'cert-inspector': lazy(() => import('@/widgets/pki/CertInspectorWidget').then((m) => ({ default: m.CertInspector }))),
  'cert-chain': lazy(() => import('@/widgets/pki/CertChainWidget').then((m) => ({ default: m.CertChain }))),
  'tls-handshake-demo': lazy(() => import('@/widgets/pki/HandshakeWidget').then((m) => ({ default: m.TlsHandshake }))),
  'cert-errors': lazy(() => import('@/widgets/pki/CertErrorsWidget').then((m) => ({ default: m.CertErrors }))),
  'ospf-demo': lazy(() => import('@/widgets/ospf/OspfWidget').then((m) => ({ default: m.Ospf }))),
  'redundancy-demo': lazy(() => import('@/widgets/redundancy/RedundancyWidget').then((m) => ({ default: m.Redundancy }))),
  'dot1x-flow': lazy(() => import('@/widgets/nac/Dot1xFlowWidget').then((m) => ({ default: m.Dot1xFlow }))),
  'nac-policy': lazy(() => import('@/widgets/nac/PolicyWidget').then((m) => ({ default: m.NacPolicy }))),
  'nac-posture': lazy(() => import('@/widgets/nac/PostureWidget').then((m) => ({ default: m.NacPosture }))),
  'nac-deployment': lazy(() => import('@/widgets/nac/DeploymentWidget').then((m) => ({ default: m.NacDeployment }))),
  'openssl-lab': lazy(() => import('@/widgets/opensslab/OpensslLabWidget').then((m) => ({ default: m.OpensslLab }))),
  'git-lab': lazy(() => import('@/widgets/gitlab/GitLabWidget').then((m) => ({ default: m.GitLab }))),
}
