"""baseline schema

Revision ID: 7a63b63c8cde
Revises: 
Create Date: 2026-07-20 20:24:25.305503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a63b63c8cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Baseline = Schema vor v1.19.0. certificate-Tabelle und participant.resume_code
    # kommen in der Folge-Revision (add_certificate_and_resume_code), damit bestehende,
    # per create_all gebaute Prod-DBs beim Adoptieren nur gestampt und dann sauber
    # nachmigriert werden.
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_kind', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_module_key'), ['module_key'], unique=False)

    op.create_table('content_module',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('workshop_key', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('title_de', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('scenario_de', sa.Text(), nullable=False),
    sa.Column('scenario_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('content_module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_module_workshop_key'), ['workshop_key'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('workshop_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_join_code'), ['join_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_course_workshop_key'), ['workshop_key'], unique=False)

    op.create_table('course_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'module_key', name='uq_course_module')
    )
    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_module_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_module_id'), ['id'], unique=False)

    op.create_table('module_disabled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'module_key', name='uq_module_disabled')
    )
    with op.batch_alter_table('module_disabled', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_disabled_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_disabled_id'), ['id'], unique=False)

    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('current_module_key', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name', name='uq_participant')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_id'), ['id'], unique=False)

    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'module_key', name='uq_progress')
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_participant_id'), ['participant_id'], unique=False)

    op.create_table('quiz_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_result_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_result_participant_id'), ['participant_id'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_id'), ['id'], unique=False)

    op.create_table('workshop',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title_de', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('summary_de', sa.Text(), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('content_block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value_de', sa.Text(), nullable=True),
    sa.Column('value_en', sa.Text(), nullable=True),
    sa.Column('widget_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_key'], ['content_module.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_module_snapshot',
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module_key'], ['content_module.key'], ),
    sa.PrimaryKeyConstraint('module_key')
    )
    op.create_table('content_quiz_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_key', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(), nullable=False),
    sa.Column('prompt_de', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('options_de', sa.JSON(), nullable=True),
    sa.Column('options_en', sa.JSON(), nullable=True),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module_key'], ['content_module.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_quiz_question')
    op.drop_table('content_module_snapshot')
    op.drop_table('content_block')
    op.drop_table('workshop')
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_id'))

    op.drop_table('trainer')
    op.drop_table('setting')
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_result_participant_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_result_id'))

    op.drop_table('quiz_result')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_participant_id'))
        batch_op.drop_index(batch_op.f('ix_progress_id'))

    op.drop_table('progress')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_id'))
        batch_op.drop_index(batch_op.f('ix_participant_course_id'))

    op.drop_table('participant')
    with op.batch_alter_table('module_disabled', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_disabled_id'))
        batch_op.drop_index(batch_op.f('ix_module_disabled_course_id'))

    op.drop_table('module_disabled')
    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_module_id'))
        batch_op.drop_index(batch_op.f('ix_course_module_course_id'))

    op.drop_table('course_module')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_workshop_key'))
        batch_op.drop_index(batch_op.f('ix_course_join_code'))
        batch_op.drop_index(batch_op.f('ix_course_id'))

    op.drop_table('course')
    with op.batch_alter_table('content_module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_module_workshop_key'))

    op.drop_table('content_module')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_module_key'))
        batch_op.drop_index(batch_op.f('ix_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comment_course_id'))

    op.drop_table('comment')
    # ### end Alembic commands ###
