# Kuratierte Linksammlung „Wissenswertes & Vertiefung" — wird am Ende der
# Kursübersicht angezeigt. Statisch wie changelog.py/company.py (kein DB-Editor).
LINKS = [
    {"category": {"de": "Nachschlagen & Grundlagen", "en": "Reference & Fundamentals"},
     "items": [
         {"title": "Cloudflare Learning Center",
          "url": "https://www.cloudflare.com/de-de/learning/",
          "desc": {"de": "Verständliche Artikel zu DNS, HTTPS, VPN, DDoS u.v.m. — gut als erste Vertiefung.",
                   "en": "Accessible articles on DNS, HTTPS, VPN, DDoS and more — a good first deep dive."}},
         {"title": "Elektronik-Kompendium: Netzwerktechnik",
          "url": "https://www.elektronik-kompendium.de/sites/net/",
          "desc": {"de": "Deutsches Standard-Nachschlagewerk — von Ethernet bis Routing sauber erklärt.",
                   "en": "German-language reference — from Ethernet to routing, cleanly explained."}},
         {"title": "How DNS Works (Comic)",
          "url": "https://howdns.works/",
          "desc": {"de": "Die komplette DNS-Auflösung als Comic — unterhaltsam und erstaunlich präzise.",
                   "en": "The complete DNS resolution as a comic — entertaining and surprisingly precise."}},
         {"title": "RFC Editor",
          "url": "https://www.rfc-editor.org/",
          "desc": {"de": "Die Original-Standards (RFCs) hinter allem aus diesem Kurs — z.B. RFC 791 (IP), RFC 9293 (TCP).",
                   "en": "The original standards (RFCs) behind everything in this course — e.g. RFC 791 (IP), RFC 9293 (TCP)."}},
     ]},
    {"category": {"de": "Werkzeuge", "en": "Tools"},
     "items": [
         {"title": "Wireshark",
          "url": "https://www.wireshark.org/",
          "desc": {"de": "Der Standard-Paketanalysator aus Modul 17 — kostenlos für Windows/macOS/Linux.",
                   "en": "The standard packet analyzer from module 17 — free for Windows/macOS/Linux."}},
         {"title": "Wireshark Sample Captures",
          "url": "https://wiki.wireshark.org/SampleCaptures",
          "desc": {"de": "Echte pcap-Mitschnitte zum Üben — DNS, DHCP, HTTP, VoIP und viele mehr.",
                   "en": "Real pcap captures for practice — DNS, DHCP, HTTP, VoIP and many more."}},
         {"title": "Nmap",
          "url": "https://nmap.org/",
          "desc": {"de": "Port-Scanner für eigene Netze: Welche Dienste laufen wo? (Nur mit Erlaubnis!)",
                   "en": "Port scanner for your own networks: which services run where? (Only with permission!)"}},
     ]},
    {"category": {"de": "Üben & Simulieren", "en": "Practice & Simulation"},
     "items": [
         {"title": "Cisco Packet Tracer",
          "url": "https://www.netacad.com/courses/packet-tracer",
          "desc": {"de": "Kostenloser Netzwerk-Simulator: Switches, Router und VLANs wie im Kurs selbst zusammenstecken.",
                   "en": "Free network simulator: wire up switches, routers and VLANs from the course yourself."}},
         {"title": "Subnetting Practice",
          "url": "https://subnettingpractice.com/",
          "desc": {"de": "Unbegrenzt generierte Subnetting-Aufgaben mit Lösungen — Modul 4 bis zum Reflex trainieren.",
                   "en": "Endless generated subnetting exercises with solutions — drill module 4 until it's reflex."}},
     ]},
    {"category": {"de": "Staunen & Weiterdenken", "en": "Wonder & Beyond"},
     "items": [
         {"title": "Submarine Cable Map",
          "url": "https://www.submarinecablemap.com/",
          "desc": {"de": "Interaktive Karte aller Unterseekabel — so hängt „das Internet“ physisch zusammen.",
                   "en": "Interactive map of all submarine cables — how “the internet” is physically connected."}},
         {"title": "Beej's Guide to Network Programming",
          "url": "https://beej.us/guide/bgnet/",
          "desc": {"de": "Der Klassiker, wenn du Netzwerkcode selbst schreiben willst (Sockets, TCP/UDP).",
                   "en": "The classic if you want to write network code yourself (sockets, TCP/UDP)."}},
     ]},
]
