# Kuratierte Linksammlung „Wissenswertes & Vertiefung" — wird am Ende der
# Kursübersicht angezeigt. Statisch wie changelog.py/company.py (kein DB-Editor).
# Pro Workshop eine eigene Sammlung (LINKS_BY_WORKSHOP).
NETWORK_LINKS = [
    {"category": {"de": "Nachschlagen & Grundlagen", "en": "Reference & Fundamentals"},
     "items": [
         {"title": "Cloudflare Learning Center",
          "url": "https://www.cloudflare.com/de-de/learning/",
          "desc": {"de": "Verständliche Artikel zu DNS, HTTPS, VPN, DDoS u.v.m. — gut als erste Vertiefung.",
                   "en": "Accessible articles on DNS, HTTPS, VPN, DDoS and more — a good first deep dive."}},
         {"title": "Elektronik-Kompendium: Netzwerktechnik",
          "url": "https://www.elektronik-kompendium.de/sites/net/",
          "desc": {"de": "Deutsches Standard-Nachschlagewerk — von Ethernet bis Routing sauber erklärt.",
                   "en": "German-language reference — from Ethernet to routing, cleanly explained."}},
         {"title": "How DNS Works (Comic)",
          "url": "https://howdns.works/",
          "desc": {"de": "Die komplette DNS-Auflösung als Comic — unterhaltsam und erstaunlich präzise.",
                   "en": "The complete DNS resolution as a comic — entertaining and surprisingly precise."}},
         {"title": "RFC Editor",
          "url": "https://www.rfc-editor.org/",
          "desc": {"de": "Die Original-Standards (RFCs) hinter allem aus diesem Kurs — z.B. RFC 791 (IP), RFC 9293 (TCP).",
                   "en": "The original standards (RFCs) behind everything in this course — e.g. RFC 791 (IP), RFC 9293 (TCP)."}},
     ]},
    {"category": {"de": "Werkzeuge", "en": "Tools"},
     "items": [
         {"title": "Wireshark",
          "url": "https://www.wireshark.org/",
          "desc": {"de": "Der Standard-Paketanalysator aus Modul 17 — kostenlos für Windows/macOS/Linux.",
                   "en": "The standard packet analyzer from module 17 — free for Windows/macOS/Linux."}},
         {"title": "Wireshark Sample Captures",
          "url": "https://wiki.wireshark.org/SampleCaptures",
          "desc": {"de": "Echte pcap-Mitschnitte zum Üben — DNS, DHCP, HTTP, VoIP und viele mehr.",
                   "en": "Real pcap captures for practice — DNS, DHCP, HTTP, VoIP and many more."}},
         {"title": "Nmap",
          "url": "https://nmap.org/",
          "desc": {"de": "Port-Scanner für eigene Netze: Welche Dienste laufen wo? (Nur mit Erlaubnis!)",
                   "en": "Port scanner for your own networks: which services run where? (Only with permission!)"}},
     ]},
    {"category": {"de": "Üben & Simulieren", "en": "Practice & Simulation"},
     "items": [
         {"title": "Cisco Packet Tracer",
          "url": "https://www.netacad.com/courses/packet-tracer",
          "desc": {"de": "Kostenloser Netzwerk-Simulator: Switches, Router und VLANs wie im Kurs selbst zusammenstecken.",
                   "en": "Free network simulator: wire up switches, routers and VLANs from the course yourself."}},
         {"title": "Subnetting Practice",
          "url": "https://subnettingpractice.com/",
          "desc": {"de": "Unbegrenzt generierte Subnetting-Aufgaben mit Lösungen — Modul 4 bis zum Reflex trainieren.",
                   "en": "Endless generated subnetting exercises with solutions — drill module 4 until it's reflex."}},
     ]},
    {"category": {"de": "Staunen & Weiterdenken", "en": "Wonder & Beyond"},
     "items": [
         {"title": "Submarine Cable Map",
          "url": "https://www.submarinecablemap.com/",
          "desc": {"de": "Interaktive Karte aller Unterseekabel — so hängt „das Internet“ physisch zusammen.",
                   "en": "Interactive map of all submarine cables — how “the internet” is physically connected."}},
         {"title": "Beej's Guide to Network Programming",
          "url": "https://beej.us/guide/bgnet/",
          "desc": {"de": "Der Klassiker, wenn du Netzwerkcode selbst schreiben willst (Sockets, TCP/UDP).",
                   "en": "The classic if you want to write network code yourself (sockets, TCP/UDP)."}},
     ]},
]

CLAUDE_LINKS = [
    {"category": {"de": "Dokumentation", "en": "Documentation"},
     "items": [
         {"title": "Claude Code — Offizielle Doku",
          "url": "https://docs.claude.com/en/docs/claude-code",
          "desc": {"de": "Installation, CLI, Hooks, Slash-Commands, Subagents — die maßgebliche Quelle.",
                   "en": "Install, CLI, hooks, slash commands, subagents — the authoritative source."}},
         {"title": "Claude Docs",
          "url": "https://docs.claude.com/",
          "desc": {"de": "Gesamte Anthropic-Doku: API, Modelle, Prompting, Tool-Use.",
                   "en": "Full Anthropic docs: API, models, prompting, tool use."}},
         {"title": "Prompt Engineering",
          "url": "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview",
          "desc": {"de": "Wie man Claude präzise instruiert — direkt übertragbar auf CLAUDE.md.",
                   "en": "How to instruct Claude precisely — carries straight over to CLAUDE.md."}},
     ]},
    {"category": {"de": "Erweitern & Anbinden", "en": "Extend & Integrate"},
     "items": [
         {"title": "Model Context Protocol",
          "url": "https://modelcontextprotocol.io/",
          "desc": {"de": "Der offene Standard hinter MCP — Server, Clients, Spezifikation.",
                   "en": "The open standard behind MCP — servers, clients, specification."}},
         {"title": "Anthropic Cookbook",
          "url": "https://github.com/anthropics/anthropic-cookbook",
          "desc": {"de": "Praktische Rezepte und Beispielcode für den Bau mit Claude.",
                   "en": "Practical recipes and sample code for building with Claude."}},
     ]},
    {"category": {"de": "Weiterdenken", "en": "Beyond"},
     "items": [
         {"title": "Anthropic Research",
          "url": "https://www.anthropic.com/research",
          "desc": {"de": "Hintergrund zu Fähigkeiten, Grenzen und Sicherheit der Modelle.",
                   "en": "Background on model capabilities, limits and safety."}},
     ]},
]

# Rückwärtskompatibel (Tests/alte Importe) — Standard bleibt die Netzwerksammlung.
LINKS = NETWORK_LINKS

INFOBLOX_LINKS = [
    {"category": {"de": "Herstellerdoku", "en": "Vendor documentation"},
     "items": [
         {"title": "Infoblox Documentation Portal",
          "url": "https://docs.infoblox.com/",
          "desc": {"de": "Die offizielle Dokumentation zu NIOS und Universal DDI — erste Anlaufstelle bei konkreten Fragen.",
                   "en": "Official documentation for NIOS and Universal DDI — the first stop for concrete questions."}},
         {"title": "Infoblox Community",
          "url": "https://community.infoblox.com/",
          "desc": {"de": "Forum mit Praxisfragen anderer Betreiber — oft findet sich hier ein Fehlerbild wieder.",
                   "en": "Forum with practitioners' questions — often the place where a symptom already has an answer."}},
     ]},
    {"category": {"de": "Standards hinter den Diensten", "en": "Standards behind the services"},
     "items": [
         {"title": "RFC 1035 — Domain Names",
          "url": "https://www.rfc-editor.org/rfc/rfc1035",
          "desc": {"de": "Der DNS-Basisstandard: Zonen, Records, Abfrageformat.",
                   "en": "The DNS base standard: zones, records, query format."}},
         {"title": "RFC 2131 — DHCP",
          "url": "https://www.rfc-editor.org/rfc/rfc2131",
          "desc": {"de": "Der DHCP-Standard mit dem vollständigen DORA-Ablauf und den Lease-Regeln.",
                   "en": "The DHCP standard with the full DORA exchange and lease rules."}},
         {"title": "ICANN: Was ist DNSSEC?",
          "url": "https://www.icann.org/resources/pages/dnssec-what-is-it-why-important-2019-03-05-en",
          "desc": {"de": "Kompakte Erklärung der Vertrauenskette — gute Ergänzung zum DNSSEC-Modul.",
                   "en": "A compact explanation of the chain of trust — a good companion to the DNSSEC module."}},
         {"title": "ISC: Response Policy Zones",
          "url": "https://www.isc.org/rpz/",
          "desc": {"de": "Ursprung und Funktionsweise der DNS-Firewall, auf der RPZ-Produkte aufsetzen.",
                   "en": "Origin and mechanics of the DNS firewall that RPZ products build on."}},
     ]},
]

ANSIBLE_LINKS = [
    {"category": {"de": "Offizielle Dokumentation", "en": "Official documentation"},
     "items": [
         {"title": "Ansible Documentation",
          "url": "https://docs.ansible.com/",
          "desc": {"de": "Referenz für Module, Plugins und Sprachelemente — das Nachschlagewerk im Alltag.",
                   "en": "Reference for modules, plugins and language elements — the day-to-day manual."}},
         {"title": "Ansible Galaxy",
          "url": "https://galaxy.ansible.com/",
          "desc": {"de": "Verzeichnis der Collections und Rollen: erst schauen, ob es das schon gibt.",
                   "en": "Directory of collections and roles: check whether it already exists."}},
         {"title": "Jinja-Template-Dokumentation",
          "url": "https://jinja.palletsprojects.com/",
          "desc": {"de": "Die Template-Sprache hinter allen Ansible-Templates und Variablenausdrücken.",
                   "en": "The template language behind every Ansible template and variable expression."}},
     ]},
    {"category": {"de": "Üben & Qualität", "en": "Practice & quality"},
     "items": [
         {"title": "Red Hat Ansible Workshops",
          "url": "https://github.com/ansible/workshops",
          "desc": {"de": "Offenes Übungsmaterial mit vollständigen Lab-Abläufen — gut zum Weiterüben nach dem Kurs.",
                   "en": "Open workshop material with complete lab flows — good for practising beyond this course."}},
         {"title": "ansible-lint",
          "url": "https://docs.ansible.com/projects/lint/",
          "desc": {"de": "Prüft Playbooks auf Stil- und Zuverlässigkeitsprobleme, bevor sie irgendwo laufen.",
                   "en": "Checks playbooks for style and reliability problems before they run anywhere."}},
     ]},
]

LINKS_BY_WORKSHOP = {
    "network": NETWORK_LINKS,
    "claude-code": CLAUDE_LINKS,
    "infoblox": INFOBLOX_LINKS,
    "ansible": ANSIBLE_LINKS,
}
