import type { Lang } from '@/lib/i18n'

export interface GlossaryTerm {
  key: string
  label: Record<Lang, string>
  description: Record<Lang, string>
  modules: string[]
}

export const GLOSSARY: GlossaryTerm[] = [
  { key: 'osi', label: { de: 'OSI-Schichten', en: 'OSI layers' }, description: { de: 'Ein Modell, das Netzwerkkommunikation in sieben Aufgabenbereiche gliedert.', en: 'A model that separates network communication into seven areas of responsibility.' }, modules: ['paket'] },
  { key: 'frame', label: { de: 'Ethernet-Frame', en: 'Ethernet frame' }, description: { de: 'Die Datenform auf Schicht 2 mit Ziel-/Quell-MAC, Typ, Nutzdaten und Fehlerprüfung.', en: 'The Layer-2 data unit with destination/source MAC, type, payload and error check.' }, modules: ['paket', 'switching'] },
  { key: 'mac', label: { de: 'MAC-Adresse', en: 'MAC address' }, description: { de: 'Eine Layer-2-Adresse, mit der Switches Frames innerhalb eines lokalen Netzes weiterleiten.', en: 'A Layer-2 address switches use to forward frames within a local network.' }, modules: ['paket', 'switching', 'arp'] },
  { key: 'vlan', label: { de: 'VLAN', en: 'VLAN' }, description: { de: 'Eine logische Trennung eines Switch-Netzes in eigene Broadcast-Domänen.', en: 'A logical separation of a switched network into distinct broadcast domains.' }, modules: ['vlan', 'wlan', 'troubleshooting'] },
  { key: 'trunk', label: { de: 'Trunk', en: 'Trunk' }, description: { de: 'Eine Verbindung, die mehrere VLANs transportiert, normalerweise mit 802.1Q-Tags.', en: 'A link that carries multiple VLANs, normally using 802.1Q tags.' }, modules: ['vlan', 'paket'] },
  { key: 'cidr', label: { de: 'CIDR-Präfix', en: 'CIDR prefix' }, description: { de: 'Die Schreibweise /24 oder /26: Sie bestimmt, wie viele Bits zum Netz gehören.', en: 'The /24 or /26 notation: it determines how many bits belong to the network.' }, modules: ['subnetting', 'routing', 'troubleshooting'] },
  { key: 'gateway', label: { de: 'Standard-Gateway', en: 'Default gateway' }, description: { de: 'Der Router im eigenen Netz, an den Pakete für fremde Netze gesendet werden.', en: 'The local router that receives packets destined for other networks.' }, modules: ['subnetting', 'arp', 'routing', 'troubleshooting'] },
  { key: 'private-ip', label: { de: 'Private IPv4-Bereiche', en: 'Private IPv4 ranges' }, description: { de: 'RFC-1918-Netze für interne Adressen: 10.0.0.0/8, 172.16.0.0/12 und 192.168.0.0/16. Sie werden im Internet nicht geroutet.', en: 'RFC 1918 ranges for internal addresses: 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16. They are not routed on the public Internet.' }, modules: ['subnetting', 'nat', 'dhcp', 'troubleshooting'] },
  { key: 'arp', label: { de: 'ARP', en: 'ARP' }, description: { de: 'IPv4 löst damit im lokalen Netz eine IP-Adresse in eine MAC-Adresse auf.', en: 'IPv4 uses it to resolve a local IP address to a MAC address.' }, modules: ['arp', 'routing', 'troubleshooting'] },
  { key: 'route', label: { de: 'Route', en: 'Route' }, description: { de: 'Ein Eintrag, der festlegt, über welchen Next Hop ein Zielnetz erreichbar ist.', en: 'An entry that determines through which next hop a destination network is reachable.' }, modules: ['routing', 'icmp', 'troubleshooting'] },
  { key: 'nat', label: { de: 'NAT/PAT', en: 'NAT/PAT' }, description: { de: 'Übersetzt private Adressen und bei PAT zusätzlich Ports für Internetverbindungen.', en: 'Translates private addresses and, with PAT, ports for internet connections.' }, modules: ['nat', 'routing', 'troubleshooting'] },
  { key: 'dns', label: { de: 'DNS', en: 'DNS' }, description: { de: 'Löst Namen wie www.example.com in IP-Adressen auf.', en: 'Resolves names such as www.example.com to IP addresses.' }, modules: ['dns', 'ports', 'troubleshooting', 'wireshark'] },
  { key: 'dhcp', label: { de: 'DHCP', en: 'DHCP' }, description: { de: 'Vergibt IP-Konfiguration automatisch und zeitlich begrenzt als Lease.', en: 'Automatically assigns IP configuration for a limited time as a lease.' }, modules: ['dhcp', 'troubleshooting'] },
  { key: 'tcp', label: { de: 'TCP', en: 'TCP' }, description: { de: 'Ein verbindungsorientiertes Transportprotokoll mit zuverlässiger, geordneter Übertragung.', en: 'A connection-oriented transport protocol with reliable, ordered delivery.' }, modules: ['ports', 'wireshark'] },
  { key: 'udp', label: { de: 'UDP', en: 'UDP' }, description: { de: 'Ein verbindungsloses Transportprotokoll ohne Zustell- oder Reihenfolgegarantie.', en: 'A connectionless transport protocol without delivery or ordering guarantees.' }, modules: ['ports', 'dns', 'wireshark'] },
  { key: 'port', label: { de: 'Port', en: 'Port' }, description: { de: 'Eine Nummer, die einen Dienst auf einem Host identifiziert.', en: 'A number that identifies a service on a host.' }, modules: ['ports', 'firewall', 'nat', 'wireshark'] },
  { key: 'icmp', label: { de: 'ICMP', en: 'ICMP' }, description: { de: 'IP-Meldungen für Fehler und Diagnose, etwa Echo Request/Reply bei ping.', en: 'IP messages for errors and diagnostics, such as ping echo requests/replies.' }, modules: ['icmp', 'troubleshooting', 'wireshark'] },
  { key: 'ttl', label: { de: 'TTL', en: 'TTL' }, description: { de: 'Ein Hop-Zähler im IP-Header; bei null wird ein Paket verworfen.', en: 'A hop counter in the IP header; when it reaches zero, a packet is discarded.' }, modules: ['icmp', 'routing'] },
  { key: 'firewall', label: { de: 'Firewall', en: 'Firewall' }, description: { de: 'Prüft Verkehr gegen Regeln, zum Beispiel nach IP, Protokoll und Port.', en: 'Checks traffic against rules, for example by IP, protocol and port.' }, modules: ['firewall', 'vlan', 'vpn', 'troubleshooting'] },
  { key: 'ipv6', label: { de: 'IPv6', en: 'IPv6' }, description: { de: 'Die IP-Version mit 128-Bit-Adressen, Neighbor Discovery und Multicast statt Broadcast.', en: 'The IP version with 128-bit addresses, Neighbor Discovery and multicast instead of broadcast.' }, modules: ['ipv6'] },
  { key: 'wlan', label: { de: 'SSID', en: 'SSID' }, description: { de: 'Der sichtbare Name eines WLANs, mit dem sich Geräte assoziieren.', en: 'The visible Wi-Fi network name that devices associate with.' }, modules: ['wlan'] },
  { key: 'vpn', label: { de: 'VPN', en: 'VPN' }, description: { de: 'Ein verschlüsselter Tunnel durch ein nicht vertrauenswürdiges Netz.', en: 'An encrypted tunnel through an untrusted network.' }, modules: ['vpn', 'troubleshooting'] },
  { key: 'capture', label: { de: 'Paketmitschnitt', en: 'Packet capture' }, description: { de: 'Aufzeichnung von Netzwerkverkehr zur Analyse, nur mit Auftrag oder Erlaubnis.', en: 'A recording of network traffic for analysis, only with authorisation or permission.' }, modules: ['wireshark'] },
  // Begriffe des Claude-Code-Workshops (Module 101–118)
  { key: 'token', label: { de: 'Token', en: 'Token' }, description: { de: 'Die kleinste Texteinheit, mit der ein Sprachmodell rechnet — oft ein Wortteil, kein ganzes Wort.', en: 'The smallest unit of text a language model works with — often a word fragment rather than a whole word.' }, modules: ['llm-grundlagen', 'cli-workflows', 'claude-md', 'hooks'] },
  { key: 'tokenization', label: { de: 'Tokenisierung', en: 'Tokenization' }, description: { de: 'Der Vorgang, einen Text in Tokens zu zerlegen und auf Zahlen abzubilden, bevor ein Modell ihn verarbeitet.', en: 'The process of splitting text into tokens and mapping them to numbers before a model processes it.' }, modules: ['llm-grundlagen'] },
  { key: 'context-window', label: { de: 'Kontextfenster', en: 'Context window' }, description: { de: 'Die maximale Menge an Tokens, die ein Modell in einem Durchgang berücksichtigt — Eingabe und Ausgabe zusammen.', en: 'The maximum number of tokens a model can consider in one pass — input and output combined.' }, modules: ['llm-grundlagen', 'cli-workflows', 'claude-md', 'subagents', 'orchestration', 'hooks'] },
  { key: 'transformer', label: { de: 'Transformer', en: 'Transformer' }, description: { de: 'Die Architektur, auf der moderne Sprachmodelle beruhen; ihr Kern ist der Attention-Mechanismus.', en: 'The architecture behind modern language models; its core is the attention mechanism.' }, modules: ['llm-grundlagen'] },
  { key: 'attention', label: { de: 'Attention', en: 'Attention' }, description: { de: 'Der Mechanismus, mit dem ein Modell beim Verarbeiten eines Tokens gewichtet, welche anderen Tokens im Kontext gerade relevant sind.', en: 'The mechanism a model uses, while processing one token, to weigh which other tokens in the context are currently relevant.' }, modules: ['llm-grundlagen'] },
  { key: 'hallucination', label: { de: 'Halluzination', en: 'Hallucination' }, description: { de: 'Plausibel klingender, aber falscher oder erfundener Inhalt, den ein Sprachmodell erzeugt — deshalb müssen Ergebnisse verifiziert werden.', en: 'Plausible-sounding but false or invented content produced by a language model — the reason results must be verified.' }, modules: ['llm-grundlagen'] },
  { key: 'agentic-coding', label: { de: 'Agentic Coding', en: 'Agentic coding' }, description: { de: 'Ein Arbeitsstil, bei dem ein Agent eine ganze Aufgabe eigenständig übernimmt: lesen, planen, ändern, testen und nachbessern.', en: 'A working style in which an agent takes on an entire task on its own: reading, planning, changing, testing and correcting.' }, modules: ['agentic-coding', 'ci-cd'] },
  { key: 'claude-md', label: { de: 'CLAUDE.md', en: 'CLAUDE.md' }, description: { de: 'Eine Markdown-Datei mit persistenten Projektanweisungen, die Claude Code zu Beginn jeder Session liest.', en: 'A Markdown file with persistent project instructions that Claude Code reads at the start of every session.' }, modules: ['agentic-coding', 'installation-setup', 'cli-workflows', 'claude-md', 'skills-commands', 'hooks', 'security-enterprise', 'ci-cd', 'capstone'] },
  { key: 'skill', label: { de: 'Skill', en: 'Skill' }, description: { de: 'Eine Datei mit wiederverwendbaren Anweisungen, die Claude Code bei passender Aufgabe automatisch lädt oder die per /name aufgerufen wird.', en: 'A file with reusable instructions that Claude Code loads automatically for a matching task or that is invoked with /name.' }, modules: ['skills-commands', 'claude-md', 'cli-workflows', 'plugins', 'spec-driven-bmad', 'ci-cd', 'capstone'] },
  { key: 'slash-command', label: { de: 'Slash-Command', en: 'Slash command' }, description: { de: 'Ein Kommando, das in der Session mit / eingeleitet wird und schnellen Zugriff auf eingebaute oder eigene Funktionen gibt.', en: 'A command entered in the session starting with / that gives quick access to built-in or custom functionality.' }, modules: ['cli-workflows', 'hooks'] },
  { key: 'plan-mode', label: { de: 'Plan-Modus', en: 'Plan mode' }, description: { de: 'Ein Modus, in dem Claude Code nur einen Plan erklärt und nichts ändert, bis er freigegeben wird.', en: 'A mode in which Claude Code only explains a plan and changes nothing until it is approved.' }, modules: ['cli-workflows', 'spec-driven-bmad', 'security-enterprise', 'effective-workflows', 'capstone'] },
  { key: 'mcp', label: { de: 'MCP', en: 'MCP' }, description: { de: 'Model Context Protocol: ein offener Standard, der KI-Werkzeuge wie Claude Code mit externen Datenquellen und Diensten verbindet.', en: 'Model Context Protocol: an open standard that connects AI tools like Claude Code to external data sources and services.' }, modules: ['mcp', 'agentic-coding', 'hooks', 'plugins', 'security-enterprise', 'capstone'] },
  { key: 'subagent', label: { de: 'Subagent', en: 'Subagent' }, description: { de: 'Ein spezialisierter Helfer mit eigenem Kontextfenster und eigenen Werkzeugrechten, der eine Nebenaufgabe erledigt und nur das Ergebnis zurückgibt.', en: 'A specialized helper with its own context window and tool permissions that handles a side task and returns only the result.' }, modules: ['subagents', 'orchestration', 'spec-driven-bmad', 'plugins', 'security-enterprise', 'capstone'] },
  { key: 'bmad', label: { de: 'BMAD', en: 'BMAD' }, description: { de: 'Breakthrough Method of Agile AI-Driven Development: eine Methodik, die KI-getriebene Entwicklung auf spezialisierte Rollen mit klar definierten Artefakten aufteilt.', en: 'Breakthrough Method of Agile AI-Driven Development: a methodology that splits AI-driven development across specialized roles with clearly defined artifacts.' }, modules: ['spec-driven-bmad'] },
  { key: 'hook', label: { de: 'Hook', en: 'Hook' }, description: { de: 'Ein Kommando, das Claude Code an einem festen Punkt im Lebenszyklus automatisch und garantiert ausführt, unabhängig davon, was das Modell entscheidet.', en: 'A command Claude Code runs automatically and reliably at a fixed lifecycle point, regardless of what the model decides.' }, modules: ['hooks', 'claude-md', 'plugins', 'mcp', 'capstone'] },
  { key: 'marketplace', label: { de: 'Marketplace', en: 'Marketplace' }, description: { de: 'Ein Katalog, meist ein Git-Repo, über den Plugins verteilt und installiert werden.', en: 'A catalog, usually a Git repo, through which plugins are distributed and installed.' }, modules: ['plugins'] },
  { key: 'worktree', label: { de: 'Worktree', en: 'Worktree' }, description: { de: 'Eine isolierte Arbeitskopie eines Git-Repositories, mit der mehrere Sessions parallel arbeiten können, ohne sich gegenseitig Dateien zu überschreiben.', en: "An isolated working copy of a Git repository that lets multiple sessions work in parallel without overwriting each other's files." }, modules: ['git-collaboration', 'subagents'] },
  { key: 'sandbox', label: { de: 'Sandbox', en: 'Sandbox' }, description: { de: 'Eine Isolierung von Datei- und Netzwerkzugriff, die begrenzt, was ein Agent überhaupt tun kann — zusätzlich zu den Berechtigungsregeln.', en: 'An isolation of file and network access that limits what an agent can do at all — in addition to the permission rules.' }, modules: ['security-enterprise', 'hooks', 'safe-ai-workflows'] },
  { key: 'prompt-injection', label: { de: 'Prompt Injection', en: 'Prompt injection' }, description: { de: 'Ein Versuch, über gelesene Inhalte wie Issues, Code oder Webseiten Anweisungen einzuschleusen, die den Auftrag oder Sicherheitsregeln überschreiben sollen.', en: 'An attempt to smuggle instructions in through content that gets read — issues, code, web pages — to override the task or safety rules.' }, modules: ['safe-ai-workflows'] },
]

export function termsForModule(moduleKey: string): GlossaryTerm[] {
  return GLOSSARY.filter((term) => term.modules.includes(moduleKey))
}
